export = xAPITrackerAsset;
declare class xAPITrackerAsset {
    constructor(endpoint: any, backup_endpoint: any, backup_type: any, actor_homePage: any, actor_name: any, auth_token: any, default_uri: any, debug: any, batchLength: any, batchTimeout: any, maxRetryDelay: any);
    xapi: any;
    endpoint: any;
    auth_token: any;
    online: boolean;
    statementsToSend: any[];
    sendingInProgress: any;
    offset: number;
    backup: boolean;
    backup_endpoint: any;
    backup_type: any;
    backupRequestParameters: any;
    actor: ActorStatement;
    actor_homePage: any;
    actor_name: any;
    context: ContextStatement;
    default_uri: any;
    debug: any;
    batchlength: number;
    batchtimeout: any;
    retryDelay: any;
    maxRetryDelay: any;
    timer: any;
    logout(): void;
    onOffline(): void;
    onOnline(): Promise<void>;
    updateAuth(): void;
    sendBatch(): Promise<void>;
    refreshAuth(): Promise<void>;
    startTimer(): void;
    Trace(verbId: any, objectType: any, objectId: any): Statement;
    sendBackup(): Promise<void>;
    enqueue(statement: any): Promise<void>;
}
import ActorStatement = require("./HighLevel/Statement/ActorStatement.js");
import ContextStatement = require("./HighLevel/Statement/ContextStatement.js");
import Statement = require("./HighLevel/Statement/Statement.js");
